### ISSUE TITLE
What is abs-file

### ISSUE THREAD

**Issue by serwaas** [basilfx/Course-Face3D#1]
I want to test this project, but I can't understand what abs-file is
Could you describe structure of this file and share examples?

**Comment by basilfx** [comment]
Hi @serwaas,

It's more than six year ago that I did this assignment, so I don't have the data files at hand. If I recall correctly, it's a file that lists some headers, and the then a x/y/z value (z being the depth). Take a look at https://github.com/basilfx/Course-Face3D/blob/master/face3d/absfile.py.

**Comment by basilfx** [comment]
I think the dataset was from here: https://www.nist.gov/programs-projects/face-recognition-grand-challenge-frgc
